language: python

# sudo false implies containerized builds
sudo: false

python:
  - 2.7

env:
  global:
    # List package dependencies for conda
    #- CONDA_DEPS="pytest numpy"
    # package name for test invocation
    - PACKAGENAME="orio"

before_install:
# Here we download miniconda and install the dependencies
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda create -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
#- conda install $CONDA_DEPS

install:
- python setup.py install

script:
#- pytest $PACKAGENAME
- cd examples 
- orcc -v axpy5.c
